### ISSUE TITLE
iOS App closes, When network connection is off

### ISSUE THREAD

**Issue by Karthik-king** [apache/cordova-plugin-network-information#75] opened 2018-10-09 13:03 UTC
**iOS App closes on Splashscreen, When network connection is off.**

If my network connection is off, i want the app shows popup contain.. "**There is no connection**."
App is not to be closed.

**Comment by janpio** [comment] 2018-10-30 11:12
What versions of everything are you using? (Cordova CLI, Cordova iOS, this plugin, iOS?)

What is your code?
Why is it closing your app?
What did you implement to get this popup you want?

**Comment by Karthik-king** [comment] 2018-10-30 14:14
Hi @janpio. I m using latest cordova CLI and cordova ios, Ios version  is 12.0,

There is  no internet connection in mobile. When open the app, the app getting force closed in splashscreen. But in android works fine.

This plugin works fine inside the app, when suddenly internet is disconnected. It triggers Offline method. But the app has initially no network, it kickout in splashscreen.

**Comment by timbru31** [comment] 2020-06-26 21:12
Closing due to lack of feedback and missing example app to reproduce. If the issue persists, please create a new one and fill in the issue template completely. Thanks!

**Closed by timbru31** 2020-06-26 21:12 UTC
Labels: platform: ios, support
